export const mockValuationAndAssessmentData = [
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 1804950,
        assessmentYear: '2013/14',
        exceptionCodeOne: null,
        marketValue: 4011000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1207440,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 1203300,
        assessmentYear: '2012/13',
        exceptionCodeOne: null,
        marketValue: 2674000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1041750,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 994500,
        assessmentYear: '2010/11',
        exceptionCodeOne: null,
        marketValue: 2210000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1134000,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 1093950,
        assessmentYear: '2011/12',
        exceptionCodeOne: null,
        marketValue: 2431000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1194390,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 3280500,
        assessmentYear: '2018/19',
        exceptionCodeOne: null,
        marketValue: 7290000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 2751620,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 3118050,
        assessmentYear: '2017/18',
        exceptionCodeOne: null,
        marketValue: 6929000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 2456510,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 2619900,
        assessmentYear: '2016/17',
        exceptionCodeOne: null,
        marketValue: 5822000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 2073560,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 2464650,
        assessmentYear: '2015/16',
        exceptionCodeOne: null,
        marketValue: 5477000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1768370,
        __typename: 'ValuationAndAssessmentData',
    },
    {
        actualExemptLandTotal: 0,
        actualExemptLandValue: 0,
        actualLandValue: 387450,
        actualTotalValue: 2379150,
        assessmentYear: '2014/15',
        exceptionCodeOne: null,
        marketValue: 5287000,
        numberOfStories: 6,
        transitionalExemptionLandTotal: null,
        transitionalExemptionLandValue: null,
        transitionalLandValue: 387450,
        transitionalTotalValue: 1495170,
        __typename: 'ValuationAndAssessmentData',
    },
];
